# Generated by Django 3.0.6 on 2020-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
