# Generated by Django 3.0.6 on 2020-05-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staff_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
